### ISSUE TITLE
Kudos on your README 🥇 👏 

### ISSUE THREAD

**Issue by kris-luminar** [stanleyhlng/mocha-multi-reporters-demo#12]
### Expected behavior
A cluttered, unfocused README.

### Actual behavior
A perfect README with exactly the info I needed!  🥇 

### Steps to reproduce the behavior

  1. go the homepage of this repo.
  2. be amazed 😮 🤩

**Comment by stanleyhlng** [comment]
I'm glad you find this README useful, thank you @kris-luminar. ❤️
